routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers as CTRL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', [CTRL\HomeController::class, 'index'])->name('home');

Route::get('/home', [CTRL\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function ($request) {
	Route::group(['middleware' => 'isUser'], function ($request) {
		Route::resource('product', CTRL\ProductController::class)->except([
    			'index', 'show'
			]);;

		Route::get('my-products', [CTRL\ProductController::class, 'myProducts'])->name('my-products');
	});

	Route::group(['middleware' => 'isAdmin'], function ($request) {
		Route::get('all-products/{user_id?}', [CTRL\ProductController::class, 'allProducts'])->name('all-products');

		Route::get('users', [CTRL\UserController::class, 'usersList'])->name('users.list');
	});
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\User;

class Product extends Model
{
    use HasFactory;    

    protected $fillable = [
        'title',
        'details',
        'image',
        'user_id'
    ];

    public function scopeByUser($qry, $user_id) {
    	return $qry->where('user_id', $user_id);
    }

    public function user() {
    	return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use \Auth;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    public $user;
    public function __construct(){
        $this->middleware(function($req, $next){
            $this->user = Auth::user();
            return $next($req);
        });
    }
    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'title' => 'required|max:255',
            'details' => 'required',
            'image' => 'required|mimes:jpg,bmp,png'
        ]);

        if ($request->hasFile('image')) {                
            $file_name = Str::random(4) . time() . "." . $request->file('image')->extension();
            Storage::putFileAs(
                'public/images', $request->file('image'), $file_name
            );
        }

        $product = $this->user->products()->create([
            'title' => $request->title,
            'details' => $request->details,
            'image' => $file_name,
            'user_id' => $this->user->id,
        ]);

        $request->session()->flash('success', 'Product added successfully!');

        return redirect()->route('my-products');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        if ($product->user()->is($this->user)) {
            return view('products.edit')->with(['product'=>$product]);
        }
        else {
            return abort(403);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $validated = $request->validate([
            'title' => 'required|max:255',
            'details' => 'required',
            'image' => 'nullable|mimes:jpg,bmp,png'
        ]);
        if ($product->user()->is($this->user)) {
            $product->title = $request->title;
            $product->details = $request->details;
            if ($request->hasFile('image')) {                
                $file_name = Str::random(4) . time() . "." . $request->file('image')->extension();
                Storage::putFileAs(
                    'public/images', $request->file('image'), $file_name
                );
                Storage::delete('public/images/'.$product->image);
                $product->image = $file_name;
            }
            $product->save();
            $request->session()->flash('success', 'Product updated successfully!');
            return redirect()->route('product.edit', ['product' => $product->id]);
        }
        else {
            return abort(403);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        if ($product->user()->is($this->user)) {
            Storage::delete('public/images/'.$product->image);
            $product->delete();
            session()->flash('success', 'Product deleted successfully!');
            return response()->json(['message'=>'Product deleted successfully']);
        }
        else {
            return abort(403);
        }
    }

    public function myProducts()
    {
        $products = Product::ByUser($this->user->id)->latest()->get();
        return view('products.list')->with(['products'=>$products]);
    }

    public function allProducts($user_id=null) {
        $products = Product::when($user_id, function($qry) use ($user_id){
                                $qry->where('user_id', $user_id);
                            })
                            ->latest()->get();
        return view('products.all-list')->with(['products'=>$products]);
    }
}

resources/views/products/all-list.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">		
		<table class="table table-bordered">
			<tr>
				<th>#</th>
				<th>Title</th>
				<th>User</th>
				<th>Image</th>
				<th>Details</th>
			</tr>
			@if ($products->count())
				@foreach($products as $key => $product)
				    <tr>
				    	<td>{{ $key+1 }}</td>
				    	<td>{{ $product->title }}</td>
				    	<td>{{ $product->user->name }}</td>
				    	<td><img src="{{ asset('storage/images/' . $product->image) }}" alt="" width="75"></td>
				    	<td>{{ $product->details }}</td>
				    </tr>
				@endforeach
			@else
				<tr>
					<td colspan="5">No products found</td>
				</tr>
			@endif
		</table>
	</div>	
@endsection

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">		

		<form action="{{ url()->route('product.store') }}" method="post" enctype="multipart/form-data">
			@csrf
			<div class="form-group">
				<label for="">Title</label>
				<input class="form-control" type="text" name="title" value="{{ old('title') ? : '' }}">
			</div>
			<div class="form-group">
				<label for="">Details</label>
				<textarea class="form-control" name="details" id="">{{ old('details') ?: '' }}</textarea>
			</div>
			<div class="form-group">
				<label for="">Image</label>
				<input class="form-control" type="file" name="image">
			</div>
			<div class="form-group">
				<button class="btn btn-primary">Add product</button>
				<a href="{{ url()->route('my-products') }}" class="btn btn-default">Back</a>
			</div>
		</form>
	</div>	
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">	

		 
		<form action="{{ url()->route('product.update', ['product'=>$product->id]) }}" method="post" enctype="multipart/form-data">
			@csrf
			{{ method_field('PATCH') }}
			<div class="form-group">
				<label for="">Title</label>
				<input class="form-control" type="text" name="title" value="{{ old('title') ? : $product->title }}">
			</div>
			<div class="form-group">
				<label for="">Details</label>
				<textarea class="form-control" name="details" id="">{{ old('details') ?: $product->details }}</textarea>
			</div>
			<div class="form-group">
				<label for="">Image</label>
				<img src="{{ asset('storage/images/'.$product->image) }}" width="75" alt="">
				<input class="form-control" type="file" name="image">
			</div>
			<div class="form-group">
				<button class="btn btn-primary">Update</button>
				<a href="{{ url()->route('my-products') }}" class="btn btn-default">Back</a>
			</div>
		</form>
	</div>	
@endsection

resources/views/products/list.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div>
			<a class="btn btn-warning" href="{{ route('product.create') }}">{{ __('Create Products') }}</a>
		</div>	<br>

		<table class="table table-bordered">
			<tr>
				<th>#</th>
				<th>Title</th>
				<th>Image</th>
				<th>Details</th>
				<th></th>
				<th></th>
			</tr>
			@if ($products->count())
				@foreach($products as $key => $product)
				    <tr>
				    	<td>{{ $key+1 }}</td>
				    	<td>{{ $product->title }}</td>
				    	<td><img src="{{ asset('storage/images/' . $product->image) }}" alt="" width="75"></td>
				    	<td>{{ $product->details }}</td>
				    	<td><a href="{{ route('product.edit', ['product'=>$product->id]) }}">Edit</a></td>
				    	<td>
				    		<a class="btn btn-danger btn-sm" onclick="deleteProduct('{{ route('product.destroy', ['product'=>$product->id])}}')">Delete</a>			    		
				    	</td>
				    </tr>
				@endforeach
			@else
				<tr>
					<td colspan="6">No products found</td>
				</tr>
			@endif
		</table>
	</div>	

	<script>
		function deleteProduct(url) {
			$.ajax({
                url: url,
                type: 'delete',
                data: {'_token': '{{ csrf_token()}}'},
                success: function( data, textStatus ){
                	console.log(data, textStatus)
                    location.reload()
                },
                error: function( jqXhr, textStatus, errorThrown ){
                	// console.log(jqXhr, textStatus, errorThrown)
                    alert('Product deleting failed')
                    location.reload()
                }
            });
		}
	</script>
@endsection